In [5]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


if __name__ == '__main__':
    inpData = np.array([[0.9], [0.1], [0.8]])
    Wih = np.array([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])
    Who = np.array([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])
    Xhid = np.dot(Wih, inpData)
    print(Xhid)
    Ohid = sigmoid(Xhid)
    print(Ohid)
    Xout = np.dot(Who,Ohid)
    Oout = sigmoid(Xout)
    print(Oout)


[[1.16]
 [0.42]
 [0.62]]
[[0.76133271]
 [0.60348325]
 [0.65021855]]
[[0.72630335]
 [0.70859807]
 [0.77809706]]
